NAME = push_swap
SRC = atoi_error.c bouble.c instruction.c instruction_times.c libft.c libft2.c list.c listdata.c main.c  search_list.c search_list2.c search_list3.c search_list4.c search_nextprev.c select_num.c  sort.c
CC = gcc

all		:$(NAME)
$(NAME)	:$(SRC)
	$(CC) $(SRC) -o $(NAME)
clean	:
	rm -f $(NAME)
fclean	:
	rm -f $(NAME)
re		:fclean all

.PHONY	:re clean fclean all