NAME = push_swap

SRC = atoi_error.c bouble.c instruction.c instruction2.c instruction3.c\
		instruction2top_times.c instruction2top.c is.c is2.c\
		libft.c libft2.c libft3.c list.c list2.c listdata.c list_count.c main.c\
		push2a.c push2b.c put_do_inst.c quick.c search_enst.c search_list.c search_list2.c search_nextprev.c\
		searchA_arrayorder.c searchB_arrayorder.c sort.c sort2A.c sortA.c sort2B.c sort3B.c sortB.c sortA_first.c

CC = gcc

all		:$(NAME)
$(NAME)	:$(SRC)
	$(CC) $(SRC) -o $(NAME)
clean	:
	rm -f $(NAME)
fclean	:
	rm -f $(NAME)
re		:fclean all

.PHONY	:re clean fclean all