NAME = push_swap
SRC = libft.c libft2.c list.c list2.c list3.c search_list.c sort.c instruction.c instruction2.c instruction2top.c insertion.c bouble.c atoi_error.c main.c list4.c
CC = gcc

all		:$(NAME)
$(NAME)	:$(SRC)
	$(CC) $(SRC) -o $(NAME)
clean	:
	rm -f $(NAME)
fclean	:
	rm -f $(NAME)
re		:fclean all

.PHONY	:re clean fclean all