NAME = push_swap
SRC = array.c atoi_error.c bouble.c double_instruction.c instruction.c instruction2.c instruction3.c instruction2top.c instruction2top2.c libft.c libft2.c libft3.c list.c list2.c listdata.c main.c out2data.c  search_list.c search_list2.c search_list3.c search_nextprev.c select_num.c  sort.c sort2.c sort3.c sortA.c sortB.c sortAB.c 
CC = gcc

all		:$(NAME)
$(NAME)	:$(SRC)
	$(CC) $(SRC) -o $(NAME)
clean	:
	rm -f $(NAME)
fclean	:
	rm -f $(NAME)
re		:fclean all

.PHONY	:re clean fclean all